language: generic

services:
  - docker

env:
  matrix:
    - VERSION=3.0
    - VERSION=4.1
    - VERSION=5.2

install:
  - curl -fsSL get.docksal.io | sh
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make && make test

after_failure:
  - make logs
